[profile.default]
src = "src"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "paris"

ffi = true     # to enable vyperDeployer calling vyper compiler
fallback_oz = true
is_system = false # Note: NonceHolder and the ContractDeployer system contracts can only be called with a special is_system flag as true
mode = "3"

[profile.default.zksync]
zksolc = "1.5.15"
enable_eravm_extensions = true # Note: System contract calls (NonceHolder and ContractDeployer) can only be called with this set to true

# Update Slither/Mythrill config files and GH actions when you update the dependencies:
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

SALT = "${SALT}"
OWNER = "${OWNER}"
ALLOW_LIST_ADDRESSES = "${ALLOW_LIST_ADDRESSES}"
PK_ACCOUNT = "${PK_ACCOUNT}"

[rpc_endpoints]
eth_mainnet = "${ETH_MAINNET_RPC_URL}"
bsc_mainnet = "${BSC_MAINNET_RPC_URL}"
matic_mainnet = "${MATIC_MAINNET_RPC_URL}"
arb_mainnet = "${ARB_MAINNET_RPC_URL}"
op_mainnet = "${OP_MAINNET_RPC_URL}"
avax_mainnet = "${AVAX_MAINNET_RPC_URL}"
ftm_mainnet = "${FTM_MAINNET_RPC_URL}"
base_mainnet = "${BASE_MAINNET_RPC_URL}"
zksync_mainnet = "${ZKSYNC_MAINNET_RPC_URL}"
abs_testnet = "https://api.testnet.abs.xyz"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.default.invariant]
fail_on_revert = false
runs = 2000
depth = 23